dist: xenial
language: cpp
os:
  - linux
arch:
  - ppc64le

services:
  - docker
addons:
  artifacts:
    paths:
      - $TRAVIS_BUILD_DIR/java/target/librocksdbjni-linux-ppc64le-musl.so
      - $TRAVIS_BUILD_DIR/java/target/librocksdbjni-linux-ppc64le.so

env:
  jobs:
    - CMD=rocksdbjavastaticdockerppc64le
    - CMD=rocksdbjavastaticdockerppc64lemusl

install:
  - sudo apt-get install -y openjdk-8-jdk || exit $?
  - export PATH=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)/bin:$PATH
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)
  - echo "JAVA_HOME=${JAVA_HOME}"
  - which java && java -version
  - which javac && javac -version

script:
  - make jclean clean $CMD
